version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "job-tailor"
      POSTGRES_PASSWORD: password
    volumes:
      - ./.database/postgres:/data
    restart: always
