export const jobs = [
  {
    id: 31,
    title: 'Senior Software Engineer',
    company: 'Acme Inc.',
    location: 'San Francisco, CA',
    source: 'LinkedIn',
    datePosted: '2023-06-01',
    compensation: '$80,000 - $120,000',
    description:
      'We are looking for an experienced software engineer to join our team. You will be responsible for designing and developing complex web applications using the latest technologies.',
    skills: ['React', 'Node.js', 'TypeScript'],
    experience: '5+ years',
  },
  {
    id: 32,
    title: 'UI/UX Designer',
    company: 'Globex Corporation',
    location: 'New York, NY',
    source: 'Glassdoor',
    datePosted: '2023-05-15',
    compensation: '$80,000 - $100,000',
    description:
      'Our growing team needs a talented UI/UX designer to help create visually stunning and user-friendly interfaces. You should have a strong portfolio and experience in design tools and prototyping.',
    skills: ['Figma', 'Adobe Creative Cloud', 'User Research'],
    experience: '3-5 years',
  },
  {
    id: 33,
    title: 'DevOps Engineer',
    company: 'Stark Industries',
    location: 'Seattle, WA',
    source: 'Remote.co',
    datePosted: '2023-06-10',
    compensation: '$60,000 - $95,000',
    description:
      'We are seeking a DevOps engineer to help automate our infrastructure and deployment processes. You should have experience with containerization, cloud platforms, and CI/CD tools.',
    skills: ['Docker', 'Kubernetes', 'AWS'],
    experience: '4+ years',
  },
  {
    id: 34,
    title: 'Product Manager',
    company: 'Stark Industries',
    location: 'Chicago, IL',
    source: 'AngelList',
    datePosted: '2023-06-05',
    compensation: '$80,000 - $120,000',
    description:
      'As a Product Manager, you will be responsible for defining the product roadmap, gathering customer requirements, and collaborating with cross-functional teams to deliver innovative solutions.',
    skills: ['Agile Methodologies', 'Product Roadmapping', 'User Research'],
    experience: '3-5 years',
  },
  {
    id: 35,
    title: 'Front-end Developer',
    company: 'Globex Corporation',
    location: 'Remote',
    source: 'Flexjobs',
    datePosted: '2023-06-01',
    compensation: '$80,000 - $100,000',
    description:
      'We are looking for a talented front-end developer to join our team. You should have a strong understanding of modern JavaScript frameworks and a passion for building responsive and accessible user interfaces.',
    skills: ['React', 'Redux', 'HTML/CSS'],
    experience: '2-4 years',
  },
  {
    id: 36,
    title: 'Backend Engineer',
    company: 'Stark Industries',
    location: 'Boston, MA',
    source: 'Hired',
    datePosted: '2023-06-15',
    compensation: '$60,000 - $95,000',
    description:
      'We are seeking an experienced backend engineer to join our team. You should have expertise in building scalable and reliable APIs using modern technologies.',
    skills: ['Node.js', 'Express', 'MongoDB'],
    experience: '4+ years',
  },
  {
    id: 37,
    title: 'Data Analyst',
    company: 'Globex Corporation',
    location: 'Remote',
    source: 'Upwork',
    datePosted: '2023-06-20',
    compensation: '$60,000 - $95,000',
    description:
      'Our data team is looking for a skilled data analyst to help us uncover insights and drive data-driven decision making. You should have experience with SQL, data visualization, and statistical analysis.',
    skills: ['SQL', 'Python', 'Tableau'],
    experience: '3-5 years',
  },
  {
    id: 38,
    title: 'Mobile Developer',
    company: 'Acme Inc.',
    location: 'Los Angeles, CA',
    source: 'Dice',
    datePosted: '2023-06-25',
    compensation: '$80,000 - $120,000',
    description:
      'We are seeking a talented mobile developer to join our team and help us build innovative mobile applications. You should have experience with either iOS or Android development.',
    skills: ['Swift', 'Kotlin', 'React Native'],
    experience: '2-4 years',
  },
  {
    id: 41,
    title: 'Senior Software Engineer',
    company: 'Acme Inc.',
    location: 'San Francisco, CA',
    source: 'LinkedIn',
    datePosted: '2023-06-01',
    compensation: '$60,000 - $95,000',
    description:
      'We are looking for an experienced software engineer to join our team. You will be responsible for designing and developing complex web applications using the latest technologies.',
    skills: ['React', 'Node.js', 'TypeScript'],
    experience: '5+ years',
  },
  {
    id: 42,
    title: 'UI/UX Designer',
    company: 'Globex Corporation',
    location: 'New York, NY',
    source: 'Glassdoor',
    datePosted: '2023-05-15',
    compensation: '$80,000 - $100,000',
    description:
      'Our growing team needs a talented UI/UX designer to help create visually stunning and user-friendly interfaces. You should have a strong portfolio and experience in design tools and prototyping.',
    skills: ['Figma', 'Adobe Creative Cloud', 'User Research'],
    experience: '3-5 years',
  },
  {
    id: 43,
    title: 'DevOps Engineer',
    company: 'Stark Industries',
    location: 'Seattle, WA',
    source: 'Remote.co',
    datePosted: '2023-06-10',
    compensation: '$80,000 - $120,000',
    description:
      'We are seeking a DevOps engineer to help automate our infrastructure and deployment processes. You should have experience with containerization, cloud platforms, and CI/CD tools.',
    skills: ['Docker', 'Kubernetes', 'AWS'],
    experience: '4+ years',
  },
  {
    id: 44,
    title: 'Product Manager',
    company: 'Stark Industries',
    location: 'Chicago, IL',
    source: 'AngelList',
    datePosted: '2023-06-05',
    compensation: '$80,000 - $100,000',
    description:
      'As a Product Manager, you will be responsible for defining the product roadmap, gathering customer requirements, and collaborating with cross-functional teams to deliver innovative solutions.',
    skills: ['Agile Methodologies', 'Product Roadmapping', 'User Research'],
    experience: '3-5 years',
  },
  {
    id: 45,
    title: 'Front-end Developer',
    company: 'Globex Corporation',
    location: 'Remote',
    source: 'Flexjobs',
    datePosted: '2023-06-01',
    compensation: '$60,000 - $95,000',
    description:
      'We are looking for a talented front-end developer to join our team. You should have a strong understanding of modern JavaScript frameworks and a passion for building responsive and accessible user interfaces.',
    skills: ['React', 'Redux', 'HTML/CSS'],
    experience: '2-4 years',
  },
  {
    id: 46,
    title: 'Backend Engineer',
    company: 'Stark Industries',
    location: 'Boston, MA',
    source: 'Hired',
    datePosted: '2023-06-15',
    compensation: '$80,000 - $100,000',
    description:
      'We are seeking an experienced backend engineer to join our team. You should have expertise in building scalable and reliable APIs using modern technologies.',
    skills: ['Node.js', 'Express', 'MongoDB'],
    experience: '4+ years',
  },
  {
    id: 47,
    title: 'Data Analyst',
    company: 'Globex Corporation',
    location: 'Remote',
    source: 'Upwork',
    datePosted: '2023-06-20',
    compensation: '$80,000 - $120,000',
    description:
      'Our data team is looking for a skilled data analyst to help us uncover insights and drive data-driven decision making. You should have experience with SQL, data visualization, and statistical analysis.',
    skills: ['SQL', 'Python', 'Tableau'],
    experience: '3-5 years',
  },
  {
    id: 48,
    title: 'Mobile Developer',
    company: 'Acme Inc.',
    location: 'Los Angeles, CA',
    source: 'Dice',
    datePosted: '2023-06-25',
    compensation: '$60,000 - $95,000',
    description:
      'We are seeking a talented mobile developer to join our team and help us build innovative mobile applications. You should have experience with either iOS or Android development.',
    skills: ['Swift', 'Kotlin', 'React Native'],
    experience: '2-4 years',
  },
  {
    id: 51,
    title: 'Senior Software Engineer',
    company: 'Acme Inc.',
    location: 'San Francisco, CA',
    source: 'LinkedIn',
    datePosted: '2023-06-01',
    compensation: '$80,000 - $100,000',
    description:
      'We are looking for an experienced software engineer to join our team. You will be responsible for designing and developing complex web applications using the latest technologies.',
    skills: ['React', 'Node.js', 'TypeScript'],
    experience: '5+ years',
  },
  {
    id: 52,
    title: 'UI/UX Designer',
    company: 'Globex Corporation',
    location: 'New York, NY',
    source: 'Glassdoor',
    datePosted: '2023-05-15',
    compensation: '$80,000 - $100,000',
    description:
      'Our growing team needs a talented UI/UX designer to help create visually stunning and user-friendly interfaces. You should have a strong portfolio and experience in design tools and prototyping.',
    skills: ['Figma', 'Adobe Creative Cloud', 'User Research'],
    experience: '3-5 years',
  },
  {
    id: 53,
    title: 'DevOps Engineer',
    company: 'Stark Industries',
    location: 'Seattle, WA',
    source: 'Remote.co',
    datePosted: '2023-06-10',
    compensation: '$80,000 - $120,000',
    description:
      'We are seeking a DevOps engineer to help automate our infrastructure and deployment processes. You should have experience with containerization, cloud platforms, and CI/CD tools.',
    skills: ['Docker', 'Kubernetes', 'AWS'],
    experience: '4+ years',
  },
  {
    id: 54,
    title: 'Product Manager',
    company: 'Stark Industries',
    location: 'Chicago, IL',
    source: 'AngelList',
    datePosted: '2023-06-05',
    compensation: '$60,000 - $95,000',
    description:
      'As a Product Manager, you will be responsible for defining the product roadmap, gathering customer requirements, and collaborating with cross-functional teams to deliver innovative solutions.',
    skills: ['Agile Methodologies', 'Product Roadmapping', 'User Research'],
    experience: '3-5 years',
  },
  {
    id: 55,
    title: 'Front-end Developer',
    company: 'Globex Corporation',
    location: 'Remote',
    source: 'Flexjobs',
    datePosted: '2023-06-01',
    compensation: '$80,000 - $100,000',
    description:
      'We are looking for a talented front-end developer to join our team. You should have a strong understanding of modern JavaScript frameworks and a passion for building responsive and accessible user interfaces.',
    skills: ['React', 'Redux', 'HTML/CSS'],
    experience: '2-4 years',
  },
  {
    id: 56,
    title: 'Backend Engineer',
    company: 'Stark Industries',
    location: 'Boston, MA',
    source: 'Hired',
    datePosted: '2023-06-15',
    compensation: '$80,000 - $120,000',
    description:
      'We are seeking an experienced backend engineer to join our team. You should have expertise in building scalable and reliable APIs using modern technologies.',
    skills: ['Node.js', 'Express', 'MongoDB'],
    experience: '4+ years',
  },
  {
    id: 57,
    title: 'Data Analyst',
    company: 'Globex Corporation',
    location: 'Remote',
    source: 'Upwork',
    datePosted: '2023-06-20',
    compensation: '$80,000 - $100,000',
    description:
      'Our data team is looking for a skilled data analyst to help us uncover insights and drive data-driven decision making. You should have experience with SQL, data visualization, and statistical analysis.',
    skills: ['SQL', 'Python', 'Tableau'],
    experience: '3-5 years',
  },
  {
    id: 58,
    title: 'Mobile Developer',
    company: 'Acme Inc.',
    location: 'Los Angeles, CA',
    source: 'Dice',
    datePosted: '2023-06-25',
    compensation: '$60,000 - $95,000',
    description:
      'We are seeking a talented mobile developer to join our team and help us build innovative mobile applications. You should have experience with either iOS or Android development.',
    skills: ['Swift', 'Kotlin', 'React Native'],
    experience: '2-4 years',
  },
];

export type Job = typeof jobs[0];
